Repository pyenv-win/pyenv-win, pull requests merged in 2021-04, with the labels that each got.

#140 fix exec
  pyenv-win/bin/pyenv.bat
  pyenv-win/libexec/pyenv-shell.bat
  pyenv-win/libexec/pyenv.vbs
  tests/test_pyenv_feature_shell.py
  tests/test_pyenv_helpers.py
Labels: enhancement

#238 Add pypy
  pyenv-win/.versions_cache.xml
  pyenv-win/libexec/libs/pyenv-install-lib.vbs
  pyenv-win/libexec/pyenv-install.vbs
Labels: new feature

#240 Improve rehash error when no version installed
  pyenv-win/libexec/libs/pyenv-lib.vbs
  pyenv-win/libexec/pyenv.vbs
  tests/test_pyenv_feature_rehash.py
Labels: enhancement

#244 Fix pyenv exec
  pyenv-win/bin/pyenv.bat
Labels: bug
